### ISSUE TITLE
Using `#[field_mutator(...)]` attribute with `DefaultMutator` derive macro.

### ISSUE THREAD

**Issue by binier** [loiclec/fuzzcheck-rs#12]
At the moment you can only use `#[field_mutator(...)]` with `make_mutator!(...)` macro.

Is it possible to allow that attribute for `DefaultMutator` macro as well to avoid duplicate struct definitions?

**Comment by loiclec** [comment]
yes, I think that is possible. My thinking initially was that `#[field_mutator(...)]` would clutter the original struct definition too much, and it is better to separate the struct definition from the definition of the mutator. But I agree it is a bit silly to only make it available via `make_mutator!`.

**Comment by binier** [comment]
Yeah makes sense. Though I'm already creating extra duplicate just to derive `DefaultMutator` on it, but I need those custom `field_mutator`s so for now have to have another duplicate definitions. That's 3 times same struct defined :smile:

**Comment by loiclec** [comment]
hm, I am not sure I understand why it would be needed to define the same struct three times. Have you tried to use `make_mutator!(..)` with the “default: true” parameter? For example:

```rust

make_mutator! {
    name: OptionMutator,
    default: true,
    type: pub enum Option<T> {
        Some(T),
        None,
    }
}
```
This will write the `DefaultMutator` trait conformance for `Option<T>`.

**Comment by binier** [comment]
Yeah but `default: true` won't work in case of `type` from separate crate, right?

**Comment by loiclec** [comment]
ahh, yes, that's true, sorry!

**Comment by loiclec** [comment]
This is possible as of fuzzcheck 0.10!
