### ISSUE TITLE
View line coverage

### ISSUE THREAD

**Issue by binier** [loiclec/fuzzcheck-rs#13]
Is there a way to view line coverage after running a fuzzer? For example with LCOV http://ltp.sourceforge.net/coverage/lcov.php

![image](https://user-images.githubusercontent.com/16461497/129700369-7315259d-1e90-4f19-9404-b7347dc5f6cc.png)

**Comment by loiclec** [comment]
AFAIK, I have all the information to create a coverage report for each test case (or all test case combined). But I still need to write that functionality, it is a work in progress.

**Comment by loiclec** [comment]
To be clear, I have always wanted to have that feature, but I am hesitating on the best way to design it. I think in about a month, I should have a first version of it released :)

**Comment by binier** [comment]
Thanks for quick responses :) Sounds great.

**Comment by loiclec** [comment]
Not a lot has changed since last week, it is essentially the same. But I have put the tool online here: https://github.com/loiclec/fuzzcheck-view

**Comment by loiclec** [comment]
oops, but I should say that I haven't yet published to crates.io the version of fuzzcheck that saves all the necessary files that `fuzzcheck-view` uses. It's only on GitHub for now

**Comment by teymour-aldridge** [comment]
Is the latest version of `fuzzcheck-view` compatible with `fuzzcheck`?

**Comment by loiclec** [comment]
I pushed a tiny update to fuzzcheck-view today that solves one incompatibility, but I need to look properly at it tomorrow. So... maybe?
