### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by teymour-aldridge** [loiclec/fuzzcheck-rs#22]
(sorry if this me being pedantic; I couldn't find the source code of the docs to submit a PR, so I opened this issue instead)

> This is quite large! To understand why this particular test case was saved, we create a new test function that runs the operations and then **print** the resulting tree.

I think this should say "prints the resulting tree" instead

**Comment by loiclec** [comment]
oops! thanks, I'll fix it :) the book isn't open source, I suppose I should publish it here someday
