### ISSUE TITLE
Please provide sponsorship information

### ISSUE THREAD

**Issue by shepmaster** [loiclec/fuzzcheck-rs#4]
> Alternatively, you could sponsor me 🥳 Then I can set aside some time every week to write fuzzcheck. 

If someone were interested in this, it’s not clear where, what, or how much is being discussed.

**Comment by loiclec** [comment]
Indeed, that wasn't clear. I have now set up a Github Sponsor page and added a sponsor button on the fuzzcheck-rs repo :)
